### ISSUE TITLE
Implement some caching mechanism for the actual data.

### ISSUE THREAD

**Issue by brantsch** [brantsch/kit-ilias-fuse#3]
1. Alleviate the problem of non-working byte serving in ILIAS.
2. Prevent unnecessary HTTP requests in case some part of an open file is read repeatedly.

**Comment by brantsch** [comment]
This issue is addressed in the cache-branch.

**Comment by janisstreib** [comment]
I've implemented a simple ring cache for files a while ago (97b8c567878b7c9bcaa872a71923e453216d1506).
